
stages:
  - build
  - deploy

build:
  stage: build
  image: node:18.13.0-alpine
  script:
    - npm install
    - npm run build
    - echo "project is building"

deploy:
  stage: deploy
  only: [ "dev" ]
  tags:
    - "frontend"
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    PROJECT_NAME: frontend
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "echo Connected"
    - docker build --build-arg VITE_BASE_URL=$VITE_BASE_URL -t $PROJECT_NAME:$CI_COMMIT_SHA .
    - ssh $SSH_USER@$SERVER_IP "docker stop $PROJECT_NAME || true"
    - ssh $SSH_USER@$SERVER_IP "docker rm $PROJECT_NAME || true"
    - docker save $PROJECT_NAME:$CI_COMMIT_SHA | ssh $SSH_USER@$SERVER_IP "docker load"
    - ssh $SSH_USER@$SERVER_IP "docker run -d --restart always --name $PROJECT_NAME -p 80:80 $PROJECT_NAME:$CI_COMMIT_SHA"